spring:
  profiles:
    active: dev
#  cache:
#    type: redis
#    redis:
#      time-to-live: 1h
#      cache-null-values: false

aliyun:
  region-id: cn-hangzhou
  access-key-id: LTAIhtBRR6ZODD7k
  secret: 0mhV4si0o7ltmwiBmuZYjSi2U6czuy

whitelist:
  user: /public/**,/login,/auth/**,/sign/**,/smsCodeLogin

project:
  global:
    name: cocoon-security
    version: 0.0.1
