spring:
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:mysql://103.45.105.120:3306/cocoon-template-demo?serverTimezone=UTC
    username: xce
    password: xce123456
    hikari:
      max-lifetime: 30000
  cache:
    type: redis
    redis:
      time-to-live: 120s
logging:
  file:
    path: ../larva/log
server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
